apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-blue-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      slot: blue
  template:
    metadata:
      labels:
        slot: blue
    spec:
      containers:
        - name: sentiment-api
          image: fa23bai0045/sentiment-api:unstable
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: logs-volume
              mountPath: /app/logs
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: sentiment-logs-pvc
