apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-green-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      slot: green
  template:
    metadata:
      labels:
        slot: green
    spec:
      containers:
        - name: sentiment-api
          image: fa23bai0045/sentiment-api:stable
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
